### ISSUE TITLE
No sample with sample button

### ISSUE THREAD

**Issue by alain01** [mambax7/mymenus#4]

**Comment by mambax7** [comment]
I just uploaded the testdata - check it out. 
FYI - these are the settings of my block:
![image](https://user-images.githubusercontent.com/613686/71754818-e6f2ef80-2e55-11ea-80f8-c575d3ab3fc2.png)

And that's how it looks like in xBootstrap:
![image](https://user-images.githubusercontent.com/613686/71754853-0d188f80-2e56-11ea-83c9-6de3c5354514.png)
