### ISSUE TITLE
Link "Go to module" on modules/mymenus/admin/blocksadmin.php

### ISSUE THREAD

**Issue by alain01** [mambax7/mymenus#5]
nothing happens

**Comment by mambax7** [comment]
I don't know what is wrong with your website, but this is what I'm having:
![image](https://user-images.githubusercontent.com/613686/71754968-7f896f80-2e56-11ea-8577-179d23f2bc03.png)

**Comment by alain01** [comment]
Yes, i have same page, but please, if you click on the link "Go to module" (on top),   is it ok for you ?

**Comment by mambax7** [comment]
"Go to module" is only for modules that have Front End. 
MyMenus exists only in the Admin, so the link doesn't do anything

**Comment by alain01** [comment]
yes, so we should disabled this link.

**Comment by mambax7** [comment]
Unfortunately, I don't have the time right now, and this is not an important issue, since it doesn't damage anything. Right now I'm fighting some real bugs, so I have to prioritize.
But again, please see if your PhpStorm can help you in fixing it :)
