### ISSUE TITLE
link on space between "edit" and "clone" on tab "blocks Admin"

### ISSUE THREAD

**Issue by alain01** [mambax7/mymenus#6]
Cause carriage return

**Comment by mambax7** [comment]
So just don't press that space :)

**Comment by alain01** [comment]
???

put your mouse between edit and clone...
See hover...

please, be trust in me.

**Comment by alain01** [comment]
It 's same trouble as here : 
https://github.com/XOOPS/XoopsCore25/commit/70ff92434ec1b83192ceee34830f67c8b0d3ed26

**Comment by mambax7** [comment]
Can you then fix it? It would be a perfect opportunity for you to test PhpStorm :)
